MqttConfig        :
  Broker          : 'broker.hivemq.com:1883'
  TopicSensor     : 'MySensor/Value'
MySqlConfig        :
  User            : 'root'
  Password        : '27112000'
  Database        : 'MY_SENSOR'
  Table           : 'MySensor'